#!/bin/bash
#---------------------------------------------------------------------
##
##=head1 SYNOPSIS
##
## Set of functions used by sorcery scripts
##
##=head1 DESCRIPTION
##
## Subroutines simply loads library files.
## See the documentation in the various library files sourced
##
##=head1 COPYRIGHT
##
## Original version Copyright 2001 by Kyle Sallee
## Additions/Corrections Copyright 2002 by the Source Mage Team
##
##=head1 FUNCTIONS
#---------------------------------------------------------------------


#---------------------------------------------------------------------
# Load libraries
for MODULE in "$SGL_LIBRARY_MODULES"/lib*[^~]; do
  . $MODULE
done
#---------------------------------------------------------------------


#---------------------------------------------------------------------
##=back
##
##=head1 LICENSE
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#---------------------------------------------------------------------

