.TH CAST 8 "August 2002" "Source Mage GNU Linux" "System Administration"
.SH NAME
cast \- installs software packages
.SH SYNOPSIS
.B cast
[options] [package1] ... [package2] ...
.SH "EXAMPLE"
To install emacs type:
.IP
.B cast
emacs
.SH "DESCRIPTION" 
.I cast
is part of the
.I sorcery
source-code package management suite. It is a command-line tool
for automatically retrieving, unpacking, compiling, installing, and
tracking software installations. 
.SH "OPTIONS"
.SS "-f, --fix"
Used to be: Discover and fix broken spells. Now removed.
.P
Use
.I cleanse --fix
instead.
.SS "-s"
First download all spells, then cast.
Normal cast behavior is to download in the background while compiling.
This disables that behavior.
.SS "--deps"
Configures the spells and determines their dependencies, but does not
compiled or installed.
.SS "--cflags, --cxxflags, --ldflags"
Set custom cflags/cxxflags/ldflags values to override those found in
arch specs, and set through the sorcery menu.
.SS "--no-opts"
Disable the use of optimization flags from arch specs and the sorcery
menu, only use those specified on the command line with --cflags,
--cxxflags, or --ldflags.
.SS "-c, --compile"
Compiles spell even if there is a compile cache in /var/cache/sorcery.
Otherwise, it would just resurrect (untar) it.
Helpful when the system configuration changes.
.SS "-r, --reconfigure"
This will prompt you again for optional dependencies
and configuration options, even those you answered before.
.SS "--from directory"
Specify an alternate directory to search for cached sources.
An alternate to /var/spool/sorcery.
Usually though, you'd just copy the source to /var/spool/sorcery.
.SS "--url URL"
Specify an alternative download url.
.SS "--pam"
re-casts all installed spells that can use Linux-PAM.
.SS "-h, --help"
Display short help.
.SH "ENVIRONMENT"
The environment is set using the sorcery configuration files.
See
.I sorcery_config(5)
.SH ADVANCED USAGE
Casting from an alternate spell cache.
.IP
cast
.B --from
/root/sgl/personal/cache
emacs
.SH "NOTES"
Do not include 
.SM version
or
.SM section
name when specifying a package. To get complete listing of software packages
type
.I gaze grimoire
.P
If spell fails during a cast, try recasting it with
.I cast -r -c
to reconfigure and recompile.
.SH "COMMENTS"
Unless the
.B -from
option is specified cast will always check the
.I /var/spool/sorcery
directory first to see if the package exists. If the package does not
exist it downloads the package via the Internet.
.SH "AUTHOR"
Original version by Kyle Sallee, and updated Thomas Stewart.
Rewritten and shortened by Karsten Behrmann.
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.PP
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
alter(8), cleanse(8), dispel(8), gaze(1), grimoire(5), scribbler(8),
scribe(8), sorcery(8), sorcery_config(5), summon(8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
