.TH SUMMON 8 "November 2007" "Source Mage GNU Linux" "System Administration"
.SH NAME
confmeld \- merges staged configuration files into the system
.SH SYNOPSIS
.B confmeld
[options]
.SH "EXAMPLE"
To merge everything type:
.IP
.B confmeld
.SH "DESCRIPTION" 
.B confmeld
is part of the
.B sorcery
source-code package management suite. It is a command-line tool
for the semiautomatical merging of staged configuration files. Spells will not
install newer versions during cast, but stage them in 
.I /var/state/sorcery/staged_configs\fR.\fP 

At the end, confmeld will resolve the simple upgrade cases and ask  
for the rest. The user will have the choice to either leave the old file intact
or install the new one over. Two similar choices will additionally backup the
respective file.

To facilitate the decision, confmeld can also show the difference between the 
two files (an unified diff).

.SH "OPTIONS"
.SS "-h, --help"
outputs short help
.SH "AUTHOR"
Original version by Jaka Kranjc.
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
alter(8), cast(8), cleanse(8), dispel(8), gaze(1), grimoire(5),
scribbler(8), scribe(8), sorcery_config(8), sorcery(8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
