.TH INVOKE 8 "January 2003" "Source Mage GNU Linux" "System Administration"
.SH NAME
invoke \- builds GUI menus from installed spells
.SH SYNOPSIS
.B invoke
[options] ...
.SH "DESCRIPTION"
.I invoke
is part of the
.SM sorcery
source-code package management suite. Invoke is the menu management system, which keeps
track of the menu items for installed spells. 
.PP
Or at least it should. It is no longer maintained and getting replaced by a
new tool,
.I bless.
.SH "NOTE"
Note that the backends for generating the menus are currently unimplemented. But it'll give
a damn good try at going through the grimoire before dumping all the data in the bit bucket.
.SH "AUTHOR"
The Source Mage GNU Linux Team (http://www.sourcemage.org)
.PP
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), grimoire(5), sorcery(8), scribe(8), summon(8), scribbler (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
