.TH RESURRECT 8 "September 2008" "Source Mage GNU Linux" "System Administration"
.SH NAME
resurrect \- installs software packages from cache tarballs
.SH SYNOPSIS
.B resurrect
[options] [package1] ... [package2] ...
.PP
.B resurrect -l|--latest|-v|--version|-h|--help
<package> [version]
.SH "EXAMPLES"
To install vim from your install cache type:
.IP
.B resurrect
vim
.PP
To install the latest vim from your install cache type:
.IP
.B resurrect --latest
vim
.PP
To install vim version 7.1 from your install cache type:
.IP
.B resurrect --version 7.1
vim
.SH "DESCRIPTION" 
.I resurrect
is part of the
.SM sorcery
source-code package management suite. It is a command-line tool
for automatically installing a package and its associated
files. 

.SH "OPTIONS"
.SS "-v, --version <version> <spell>"
Remove the selected spell and restore to the given previously installed version.
The version parameter is optional and specifies preference. The user will be
shown a list of versions to choose from (unless there is only one).
.SS "-l, --latest <spell> [spell2] [spell3]"
installs the latest cached version of the spell(s)
.SS "-h, --help"
outputs short help
.SH "AUTHOR"
Original version by Jaka Kranjc
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
alter(8), cast(8), confmeld(8), cleanse(8), gaze(1), grimoire(5), scribbler(8), scribe(8),
sorcery(8), sorcery_config(5), summon(8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
