.TH SCRIBE 8 "January 2003" "Source Mage GNU Linux" "System Administration"
.SH NAME
scribe \- tracks, adds and removes grimoires
.SH SYNOPSIS
.BI "scribe add|update" " <grimoire> " [[from] " <source url> " ]
.PP
.BI "scribe fix|reindex|remove" " <grimoire> ..."
.PP
.BI "scribe index "
.PP
.BI "scribe set|swap " "<grimoire> <another grimoire>"
.PP
.BI "scribe [un]localize" "<grimoire> "
.PP
.SH "DESCRIPTION"
.I scribe
is part of the
.I sorcery
source-code package management suite.
Scribe is a utility for controlling the grimoires in your codex,
and the spells in your grimoires.

The main use of scribe is simply to update the grimoires by
.BR "scribe(8) update" "; this can be automated or invoked indirectly through"
.BR "sorcery(8) system-update" .
It is also used to get the grimoires into the codex in the first place, using
.BR "scribe(8) add" .
For example, you may want to add the grimoire called
.I waldo
from
.IR "http://zyzzy/waldo.tar.bz2" ", then you would run"
.PP
.B "scribe add waldo from http://zyzzy/waldo.tar.bz2"
.PP
.B "scribe add stable from rsync://www.sourcemage.org::stable"
.PP
It should be noted that the source url listed above can be any source such as
cvs, rsync, http, ftp, etc.
.SH "GRIMOIRE NAMES"
Grimoires are internally represented by the full path to them. They can be uniquely described on the command line by listing the name and however many subdirectories are needed to form a unique name.
.PP
For example you may have two grimoires:
.PP
.B /var/lib/sorcery/codex/stable
.PP
and
.PP
.B /root/grimoires/stable
.PP
These can be uniquely identified with
.B "codex/stable "
and
.B "grimoires/stable "
.PP
If just
.B "stable "
was specified it would match the first of the two grimoires listed in scribe index.
.PP
.SH "OPTIONS"
With each of these command line options, it is only necessary to specify enough of the verb to disambiguate
the command from the others. For example,
.IR "scribe u" " is equivalent to "
.IR "scribe up" "; both are shorthands for the long version " "scribe update"
.PP
.B scribe index
.PP
Displays a list of all currently used grimoires, in order. If reindexed then
scribe rebuilds the spell location indexes for sorcery.
.PP
.BI "add " grimoire
.PP
Downloads and adds the specified grimoire from the default location
(usually 
.BR "http://codex.sourcemage.org/grimoire-name.tar.bz2" ).
.PP
.BI "add " grimoire " from " url
.PP
Downloads and installs the grimoire
.I grimoire
from the URL given by
.IR url .
This is the complete path to the file, including the filename and the 
.B .tar.bz2
file extension.
.PP
.BI "scribe update"
.PP
Updates all installed grimoires.
.PP
.BI "scribe update " grimoire
.PP
Updates the grimoire specified by
.IR grimoire .
.PP
.BI "scribe update " grimoire " from " url
.PP
Updates the grimoire specified by
.IR grimoire " from the url " url .
.PP
.BI "scribe reindex"
.PP
Rebuild all grimoire's spell lookup tables.
.PP
.BI "scribe reindex " grimoire ...
.PP
Rebuild specified grimoire's spell lookup tables. This must be done if
a spell is added or removed from a grimoire. This is done automatically
on scribe update and scribe add.
.PP
.BI "scribe fix"
.PP
Repairs a grimoire's metadata (url to download from).
.PP
.BI "scribe remove " grimoire
.PP
Deletes the grimoire.
.IR grimoire " from the codex."
.PP
.BI "scribe set " "grimoire1 grimoire2"
.PP
Set grimoire1 before grimoire2
.PP
.BI "scribe swap " "grimoire1 grimoire2"
.PP
Changes the order the specified grimoires are listed in the
.I index
by swapping their positions.
.PP
.SH "AUTHOR"
The Source Mage GNU Linux Team <http://www.sourcemage.org>
.PP
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), grimoire(5), invoke(8), sorcery(8), summon(8), scribbler (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
