.TH SCRIBBLER 8 "October 2003" "Source Mage GNU Linux" "System Administration"
.SH NAME
scribbler \- a utility for controlling the spells in your grimoires
.SH SYNOPSIS
.B scribbler add|remove spell from-grimoire to-grimoire [to-section]
.SH "DESCRIPTION"
.I scribbler
is part of the
.SM sorcery
source-code package management suite. Scribbler is a utility for controlling the
spells in your private grimoire. 
.SH "NOTE"
The 'to-grimoire' optioin is not used for the remove command.  If 'to-section'
is not specified, then the spell will be placed in a section named the same as
the one it came from.
.SH "AUTHOR"
The Source Mage GNU Linux Team (http://www.sourcemage.org)
.PP
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), grimoire(5), sorcery(8), scribe(8), summon(8), invoke (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
