.TH SORCERY "8" "August 2001" "Source Mage GNU Linux" "System Administration"
.SH NAME
sorcery \- menu-driven software package management utility
.SH SYNTAX
.I sorcery
[update|rebuild]
.SH "DESCRIPTION"
.I sorcery
is an easy-to-use menu-driven (dialog-based) interface to the
.I sorcery
source-based package management system.
.SH "OPTIONS"
.I sorcery
without options will start the menu-driven package management utility.
.PP
.I -u|update
.IP
Updates the sorcery scripts only. This option is non-interactive and does not start up the  menu-driven interface. It is suitable for use in cron jobs.
.PP
.I -s|system-update
.IP
Perform a system update (updates sorcery, grimoire, and spells).
[ scribe update, sorcery queue, cast --queue ]
This option is non-interactive and does not start up the menu-driven interface.
It is suitable for use in cron jobs.
.PP
.I -g|upgrade
.IP
Update spells without first updating the grimoire.
[ sorcery queue, cast --queue ]
This option is non-interactive and does not start up the menu-driven interface.
It is suitable for use in cron jobs.
.PP
.I -q|queue
.IP
Compare installed grimoire to installed spells, generate queue of spells needing to be updated.
This option is non-interactive and does not start up the menu-driven interface.
It is suitable for use in cron jobs.
.PP
.I -r|rebuild
.IP
Automatically rebuilds all installed software packages. This option
is non-interactive and does not start up the menu-driven interface.
It is suitable for use in cron jobs and is useful for rebuilding
distributed binaries from source.
.PP
.I show-held
.IP
Lists all spells that are held. This option is non-interactive and does not start up the menu-driven interface.
.PP
.I hold <spell|s>
.IP
sets <spell|s> to held.
This option is non-interactive and does not start up the menu-driven interface.
.PP
.I unhold <spell|s>
.IP
unholds <spell|s>, sets them to installed.
This option is non-interactive and does not start up the menu-driven interface.
.PP
.I -v|--version 
.IP
Displays the version number of your sorcery package.
.PP
.I -h|--help
.IP
Displays some help message.
.PP
.SH "REQUIREMENTS"
.I Sorcery
requires a connection to the Internet
.PP
.I Bash
version 2 or higher
.PP
.I Dialog
version 0.9a or higher
.PP
.I Linux
kernel version 2.4.x
.SH "NOTES"
Options on the
.I Package Menu
add or remove software packages to/from installation and removal queues.
The actual installation and/or removal of the packages will not be
performed until either
.I Foreground Execution
or
.I Background Execution
are selected from the main menu.
.SH "OPERATION"
.I Navigating the Menus
.PP
To return to a previous menu press
.I <Esc>
or use the
.I Cancel
button
.PP
To exit the program from the main menu press
.I <Esc>
or use the
.I Cancel
button
.PP
To toggle between buttons press
.I <Tab>
.PP
To select whichever button is highlighted press
.I <Enter>
.PP
To select/deselect items from a checklist press
.I <Space>
.SH "AUTHOR"
Original version by Kyle Sallee, and updated Thomas Stewart.
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), grimoire(5), invoke(8), scribe(8), summon(8), scribbler (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY


