.TH SUMMON 8 "January 2002" "Source Mage GNU Linux" "System Administration"
.SH NAME
summon \- downloads spell source files
.SH SYNOPSIS
.B summon
.PP
.B summon
spell_1 spell_2 spell_2
.PP
.B summon
(--from|--url) spell_1 spell_2 spell_2
.SH "EXAMPLE"
To download emacs type:
.IP
.B summon
emacs
.SH "DESCRIPTION" 
.I summon
is part of the
.SM sorcery
source-code package management suite. It is a command-line tool
for automatically downloaing a packages associated source files. 
.SH "OPTIONS"
.TP
.B summon
.PP
By its self it tries to download every single package (about 1.2G as of 
17/02/02).
This is usefull if you have a fast link or want to test everything.
.TP
.B summon
spell_1 <spell_2> <spell_3>
.PP
This automatically downloads the specified spell sources.
.TP
.B summon
--from spell
.PP
This specifies a differant
.I /var/spool/sorcery
directory. This is the default locations for downloaded sources,
.TP
.B summon
--url
.PP
This tries to download the specified spell from a different location. This is
usefull if the original link is down.
.TP
.B "-h, --help"
outputs short help
.SH "FILES"
.TP
.I /etc/sorcery/config & /etc/sorcery/local/config
.IP
These files store the settings for default locations. Its best to leave
these be as there are in quite good places by default. See cast.8 for more
details about these files.
.IP
Contains functions used by 
.B dispel
.SH ADVANCED USAGE
Specifiing a differnt download location for linux
.IP
summon
.B --url 
http://ftp.mirror.ac.uk/sites/ftp.kernel.org/linux/kernel/2.4/linux-2.4.16.tar.bz2 linux
.SH "NOTES"
Do not include 
.SM version
or
.SM section
when specifying a package. To get complete listing of installed software
packages and versions type
.B gaze installed
.SH "AUTHOR"
Original version by Thomas Stewart.
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), grimoire(5), invoke(8), sorcery(8), scribe(8), scribbler (8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY
