#!/bin/bash
#---------------------------------------------------------------------
##
##=head1 SYNOPSIS
## 
## Url handler functions for grabbing directory urls.
##
##=head1 DESCRIPTION
##
## This type of url was added as a response to the following request:
##
##   I'm an AbiWord developer, and I keep the latest source 
##   tree in my abi directory. If I could make the abi spell 
##   (not to be confused with the abispell) use my current 
##   CVS checked-out tree, that would  be nice.
##
## This file contains functions for I<downloading> (actually it just
## copies, tars, and compresses) directories which can be accessed 
## through the local file system.
##
## Url's of this type are specified using the format 
##
##  dir://<directory>
##
## where <directory> is the full path to a directory that will be
## tarred and compressed for use by sorcery in casting a spell.
##
##=head1 COPYRIGHT
##
## Copyright 2002 by the Source Mage Team
##
##=head1 FUNCTIONS
##
##=over 4
##
#---------------------------------------------------------------------


#---------------------------------------------------------------------
##=item url_dir_strip_prefix <url>
# 
# Private function.  Strips off the dir:/[//] prefix from dir urls
#
#---------------------------------------------------------------------
function url_dir_strip_prefix() {
  echo $1 | sed 's/^dir:\/\///' | sed 's/^dir://'
}


#---------------------------------------------------------------------
##=item url_dir_download <url>
## 
## Copies the specified dir url.
##
#---------------------------------------------------------------------
function url_dir_download() {

  local DIRNAME=`url_dir_strip_prefix $1`

  local S_FILE=`echo $SOURCE          | 
                sed "s/\.tar\.gz$//"  |
                sed "s/\.tgz$//"      |
                sed "s/\.tar\.bz2$//"`
  rm  -f  $S_FILE.tar.gz  $S_FILE.tgz  $S_FILE.tar.bz2

  if  [  -d  "$DIRNAME"  ]; then

    local S_DIR=`echo $SOURCE_DIRECTORY | sed "s#$BUILD_DIRECTORY/##"`
    cp  -aR  $DIRNAME     $S_DIR  &&
    tar  cf  $S_FILE.tar  $S_DIR  &&
    rm  -rf  $S_DIR               &&
    bzip2    $S_FILE.tar          &&
    FILE=$S_FILE.tar.bz2          &&
    echo  "Finished."

  else

    echo  "Failed."  &&
    false

  fi

}


#---------------------------------------------------------------------
##=item url_dir_verify <url>
## 
## Verifies the specified directory exists.  Returns true if the 
## directory exists OR if the dir is an empty string.
##
#---------------------------------------------------------------------
function url_dir_verify() {

  DIRNAME=`url_dir_strip_prefix $1`
  if  [  -n  "$DIRNAME"  ]; then
      [  -d  "$DIRNAME"  ]
  fi
}

#---------------------------------------------------------------------
##=item url_dir_hostname <url>
##
## Assume that the directory is on localhost, someday this should
## check to see if the directory is on a networked filesystem.
##
#---------------------------------------------------------------------
function url_dir_hostname(){
  echo localhost
}

#---------------------------------------------------------------------
##=item url_dir_netselect <url>
##
## fake netselect data on the assumption that the data is on the
## localhost
##
#---------------------------------------------------------------------
function url_dir_netselect() {
  local each
  for each in $@; do
    echo "0 $each"
  done
}


#---------------------------------------------------------------------
##=back
##
##=head1 LICENSE
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#---------------------------------------------------------------------

