.TH GRIMOIRE 5 "August 2002" "Source Mage GNU Linux" "File Formats"
.SH NAME
grimoire \- the software catalogue for sorcery
.SH "DESCRIPTION"
The software catalogue is a list of software packages (simply referred to
as "packages") divided into sections. Each package contains one
or more description files. Description files contain such information as
package name, version, URL, directory information, etc. Other description files 
provide unpacking, compilation, installation, and tracking instructions. One 
section in the 
software catalogue of particular interest is PROFILES. Profiles are
groups of packages. With profiles you can automatically install predefined or
custom-built package sets using a single command.
.SH "SUMMARY"
The grimoire is found under /var/lib/sorcery. The top level of directories
are the section names. The directories under the section names are the
packages. Each package directory will have a BASH description file called
DETAILS and optionally contain one or more of the following description
files: PRE_BUILD, BUILD, POST_BUILD, POST_INSTALL, DEPENDS. If a description 
file does not exist in
the package directory then a set of default description instructions are
used. The default instructions for each description file can be found in 
/etc/sorcery/subroutines.
.SH "DETAILS"
\fBPROFILES\fR
.PP
Each profile contains a simplified DETAILS file: profile name, version, and
description. Profiles are effectively just a DEPEND file with a list of
packages to be installed. 
.PP
\fBDESCRIPTION FILES\fR
.PP
A better description of these file are found on the website, under the spell 
howto.
.PP
A typical source code installation might look like this (assume the
application is called foo):
.IP
step 1) find the URL and download the tarball
.IP
step 2) tar xvfz foo-1.00.tar.gz
.IP
step 3) cd foo
.IP
step 4) less README (perhaps you skip this step?)
.IP
step 5) less INSTALL (... and this one?)
.IP
step 6) ./configure
.IP
step 7) make
.IP
step 8) make install
.PP
.PP
Here is a breakdown of the description files and how they relate to the above
installation procedure:
.PP
\fBDETAILS\fR
.IP
This file is required and describes the URL for step 1. It also contains version 



information,
package name, source name, source directory, and a description of the package.
.PP
\fBCONFIGURE\fR
.IP
The configure script.
.PP
\fBDEPENDS\fR
.IP
This file contains a list of other packages upon which the package depends.
If dependencies are turned on then the packages listed are installed in order
prior to installing package.
.PP
.PP
\fBCONFLICTS\fR
.IP
Contains a list of spells that conflict with this. Use very sparingly. A good 
example of a good
use is when u have 2 packages in the grimoire that are the same but one is 
patched. eg apache and apache-mod_ssl
.PP
\fBPRE_BUILD\fR
.IP
This describes the unpacking process as performed in step 2. The default 
PRE_BUILD will work for
tarballs with gzip or bzip2 compression.
.PP
\fBBUILD\fR
.IP
This describes the compilation and installation processes as performed in steps 
6-8. If the
software package compiles and installs using these 3 steps then the default
BUILD can be used. 
.PP
\fBPOST_BUILD\fR
.IP
The default POST_BUILD simply calls the software tracking script. 
.PP
\fBPOST_INSTALL\fR
.IP
There is no default POST_INSTALL. If no POST_INSTALL is present in the
package directory no operations are not performed. 
.PP
\fBPOST_REMOVE\fR
.IP
Done after remove.
.PP
.SH "NOTES"
The best way to learn the software catalogue is to examine some of the
description files yourself. Most software catalogue entries are simple. For
example try looking under /var/lib/sorcery/grimoire/editors/emacs.
If however you want to look at a very unusual, but much more complex example 
look at
/var/lib/sorcery/grimoire/x11/xfree86. To understand how the software
catalog works it is also important to look at /etc/sorcery/subroutines and
examine the functions default_pre_build, default_build, and default_post_build.
.SH "AUTHOR"
Original version by Kyle Sallee, and updated Thomas Stewart.
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
.PP
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), dispel(8), gaze(1), invoke(8), sorcery(8), scribe(8), summon(8)
.PP
.SH "WARRANTY"
.PP
This is free software with ABSOLUTELY NO WARRANTY

