#!/bin/bash
#---------------------------------------------------------------------
## @Synopsis merge the config files located in the config stage directory to the system.
## @Copyright Other additions/corrections Copyright 2002 by the Source Mage Team
## Script to install staged config files.
#---------------------------------------------------------------------

#-----
## Help... hmm... I wonder what it does...
#-----
function help()
{
  cat << EOF

Melds the staged config files from $CONFIG_STAGE_DIRECTORY

Example:                confmeld

Optional Parameters:

            None at the moment

EOF
  exit 1
}

#--------------------------------------------------------------------
## List all the configs in the config stage root
## 
## @stdout a list of all configs in the config stage root
#--------------------------------------------------------------------
function all_config_files()
{
  find $CONFIG_STAGE_DIRECTORY
}

#--------------------------------------------------------------------
## List all uniq config files in the config stage directory
##
## @stdout a list of all uniq configs in the stage directory
#--------------------------------------------------------------------
function all_uniq_config_files()
{
  all_config_files |
  while read file
  do
    echo ${file%.*}
  done | uniq
}

#--------------------------------------------------------------------
## Main
## 
## No real arguments get all the config files and start installing
## them to the system using install_config_file
#--------------------------------------------------------------------
function main()
{
  local target
  all_config_files | 
  while read file
  do
    target=${file/$CONFIG_STAGE_DIRECTORY/}
    target=${target%.*}
    if [[ -f $file ]]
    then
      install_config_file $file $target
    fi
  done
}


. /etc/sorcery/config
main "$@"

#---------------------------------------------------------------------
##=back
##
##=head1 LICENSE
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#---------------------------------------------------------------------
