#!/bin/sh
############################################################
# This is just a temp frontend to the new "summon"         #
############################################################

summon  $*

echo  "*** PLEASE NOTE: leach is deprecated, please use summon! ***"
