#!/bin/bash



#---------------------------------------------------------------------
##=item add_depends
##
## Adds a dependency to the DEPENDS_STATUS file.  Returns 1 is the 
## 3rd or 4th fields are not valid.
##
## =over 4
## =item Format is:
## =item
## $1 - Name of the "parent" spell
## =item
## $2 - Name of the spell the parent spell depends on
## =item
## $3 - "on" or "off" depending on whether the user installed the dependency
## =item
## $4 - Type of dependency (required or optional)
## =item
## $5 - option to pass to C<configure> if the dependency is installed
## =item
## $6 - option to pass to C<configure> if the dependency is not installed
##
## =item Example:
## add_depends kdelibs alsa-driver on optional --with-alsa --without-alsa
## =back
##
#---------------------------------------------------------------------
function add_depends()
{ # $1=spell, $2=depends, $3=on/off, $4=optional/required, $5=on arg, $6=off arg
	debug "libstate" "add_depends() - $*"
	#Locking the file at the start to avoid multiple casts adding the same thing
	#lock_file $DEPENDS_STATUS  Locking done in run_depends now

	#already here for some reason
	search_depends_status_exact "$@" >/dev/null  && return 0
	
	#remove stale depends info
	search_depends_status "$@" >/dev/null && remove_depends_status "$@"
	
	#ensure the info is valid (perhaps add check that spells exist?)
	if ( [[ $3 != on ]]       && [[ $3 != off ]]       )   ||
           ( [[ $4 != required ]] && [[ $4 != optional ]]  )
	then
	  # unlock_file $DEPENDS_STATUS  Locking done in run_depends now
	  return 1 
	fi
	
	echo "$1:$2:$3:$4:$5:$6" >> $DEPENDS_STATUS
	#unlock_file $DEPENDS_STATUS  Locking done in run_depends now
	
	return 0	

}


#---------------------------------------------------------------------
#-item search_depends_status_exact
##
## In case you want to search in all the fields of the 
## DEPENDS_STATUS
##
## Arguments can be regexp
##
## Prints out the matching line(s)
##
#---------------------------------------------------------------------
function search_depends_status_exact()
{ # $1=spell, $2=depends, $3=on/off, $4=optional/required, $5=on arg, $6=off arg

	local a1 a2 a3 a4 a5 a6
	a1=`esc_str "$1"` ; a2=`esc_str "$2"` ; a3=`esc_str "$3"` ; a4=`esc_str "$4"`; a5=`esc_str "$5"`; a6=`esc_str "$6"`
debug "DB" "search_depends_status_exact: [$a1:$a2:$a3:$a4:$a5:$a6]"
	grep "^$a1:$a2:$a3:$a4:$a5:$a6$" $DEPENDS_STATUS

}


#---------------------------------------------------------------------
#-item search_depends_status
##
## In case you want to search by spell or dependancy in 
## DEPENDS_STATUS
##
## Arguments can be regexp
##
## Prints out the matching line(s)
##
#---------------------------------------------------------------------
function search_depends_status()
{ # $1=spell, $2=(opt)depends

	[ $# -eq 1 ] && grep "^`esc_str $1`:" $DEPENDS_STATUS
	[ $# -eq 2 ] && grep "^`esc_str $1`:`esc_str $2`:" $DEPENDS_STATUS

}



#---------------------------------------------------------------------
#-item get_depends_options
##
## Returns a list of options for ./configure from DEPENDS_STATUS
## If the second argument is given, returns options for the
## matching pair of spell:dependency
## Primarily aimed at generating $OPTS contents
##
## Prints out one line of output
##
#---------------------------------------------------------------------
function get_depends_options()
{ # $1=spell [$2]=dependency spell
  [ -z "$1" ] && {
    message "${PROBLEM_COLOR}${1:-<null>} is not a spell name${DEFAULT_COLOR}"
    return
  }

  local START="$(esc_str $1):"
  [ -n "$2" ] && START="${START}$(esc_str $2):"
  debug "libstate" "get_depends_options() - START=$START"
  awk -F ':' "/^$START/ { if (\$3 == \"on\") OPTS = OPTS \" \" \$5; else OPTS = OPTS \" \" \$6; } END { print OPTS; }" $DEPENDS_STATUS
}


#---------------------------------------------------------------------
#-item remove_depends_status
##
## Arguments can be regexp, and all but the spell are optional
##
#---------------------------------------------------------------------
function remove_depends_status()
{ # $1=spell, $2=(OPT)depends, $3=(OPT)on/off, $4=(OPT)optional/required, $5=(OPT)on arg, $6=(OPT)off arg

	local a1 a2 a3 a4 a5 a6
	a1=`esc_str $1` ; a2=`esc_str $2` ; a3=`esc_str $3` ; a4=`esc_str $4`; a5=`esc_str $5`; a6=`esc_str $6`
	
	a2=${a2:-.*}
	a3=${a3:-.*}
	a4=${a4:-.*}
	a5=${a5:-.*}
	a6=${a6:-.*}

	sedit "/^$a1:$a2:$a3:$a4:$a5:$a6$/D" $DEPENDS_STATUS

}


#---------------------------------------------------------------------
#-item add_spell_status
##
## Adds an entry to the SPELL_STATUS file
##
## Argumnets may either be SPELL, ACTION, VERSIONS, or just
## ACTION if there exists SPELL and VERSIONS variables already
## set.
##
#---------------------------------------------------------------------
function add_spell_status()
{ #$1=spell, $2=action, $3=version, OR $1=action.

  local spell action version date
  if [ $# -eq 1 ] ; then
    spell="$SPELL"
    action="$1"
    version="$version"
  else
    spell=$1
    action=$2
    version=$3
  fi
  [[ $spell ]] || [[ $action ]] || [[ $version ]] || return 1
  date=`date +%Y%m%d`
  tSPELL_STATUS=`lock_start_transaction $SPELL_STATUS`
  echo "$spell:$date:$action:$version" >> $tSPELL_STATUS
  lock_commit_transaction $SPELL_STATUS

}



#---------------------------------------------------------------------
#-item query_spell_status
##
## Searches the SPELL_STATUS file for a spell and optionaly
## a version.
##
## Prints out th matching entries
## Returns the result of the search
##
#---------------------------------------------------------------------
function query_spell_status()
{ #$1=spell, $2=(OPT)version

	local version spell
	version=`esc_str ${2:-".*"}`
	spell=`esc_str $1`

	tac $SPELL_STATUS | grep -m 1 "^$spell:.*:.*:$version$" | \
		cut -d ":" -f 3
		
	return $?

}


#---------------------------------------------------------------------
#-item remove_spell_status
##
## Removes all specified offending entries in SPELL_STATUS
##
#---------------------------------------------------------------------
function remove_spell_status()
{ #$1=spell to remove status of

  tSPELL_STATUS=`lock_start_transaction $SPELL_STATUS`
  grep  -v  "^$1:" $SPELL_STATUS  >  $tSPELL_STATUS
  lock_commit_transaction $SPELL_STATUS
    
}


#---------------------------------------------------------------------
#-item all_spell_status
##
## Just here to round out the SPELL_STATUS functions so that
## SPELL_STATUS doesn't have to mentioned in libsorcery
##
#---------------------------------------------------------------------
function all_spell_status()
{

  cat $SPELL_STATUS

}


#---------------------------------------------------------------------
#=item modify_local_config variable value [command]
##
## Modifies (or adds) an entry in the local/config.
## If "command" is the third argument, a space will separate the 
## variable and value rather than the equals sign.
##
#---------------------------------------------------------------------
function modify_local_config()  {

  debug "libstate" "modify_local_config() - $*"
  
  if ! [[ $1 ]]; then
    debug "libstate" "modify_local_config() - Warning: No name given for config option."
    return 1
  fi
  
  local TEMP separator EQUALS_COL
  
  # what to use as separator?
  if [[ $3 == command ]] 
  then separator=" " 
  else separator="=" ; fi
  
  # remove previous reference
  tLOCAL_CONFIG=`lock_start_transaction $LOCAL_CONFIG`
  grep  -v  "^[[:blank:]]*${1}${separator}" $LOCAL_CONFIG >  $tLOCAL_CONFIG

  # justifying...
  EQUALS_COL=$((20-${#1}))
  [ $EQUALS_COL -lt 0  ] && EQUALS_COL=0
  TEMP=""
  for (( ; EQUALS_COL>0 ; EQUALS_COL-- )) ; do
    TEMP="$TEMP "
  done
  
  debug "libstate" "modify_local_config() - entering new value into $tLOCAL_CONFIG"
  # put new value and justification in
  echo  "${TEMP}${1}${separator}\"${2}\""  >>  $tLOCAL_CONFIG

  lock_commit_transaction $LOCAL_CONFIG
    
}


#---------------------------------------------------------------------
##=back
##
##=head1 LICENSE
##
## This software is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this software; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
##
#---------------------------------------------------------------------
