.TH GAZE "1" "August 2004" "Source Mage GNU Linux" "User Commands"
.SH NAME
gaze \- query/view sorcery package management information
.PP
.SH SYNOPSIS
.PP
.B gaze
-q
.PP
.B gaze
alien|prune|pam|orphans
.PP
.B gaze
activity|install-queue|remove-queue|show\-held|show\-exiled
.PP
.B gaze
short|what|where|website|url|sources|source\_urls <spell>
.PP
.B gaze
compile|version|versions|sum|md5sum|size <spell>
.PP
.B gaze
install|install-full|install-spell <spell>
.PP
.B gaze
maintainer <section>
.PP
.B gaze
license  spell|section|license
.PP
.B gaze
export|import [snapshot]
.PP
.B gaze
grimoire [grimoire-name] 
.PP
.B gaze
grimoires
.PP
.B gaze
html [-s] [grimoire-name]  
.PP
.B gaze
search [-name|-short] "phrase"
.PP
.B gaze
newer|older [yyyymmdd]
.PP
.B gaze
service port|acronym
.PP
.B gaze
provides feature
.PP
.B gaze
from <path/file>
.PP
.B gaze
installed [spell]
.PP
.B gaze
section [section]
.PP
.B gaze
voyeur [delay | spell]
.PP
.B gaze
SCRIPT NAME <spell>
.PP
.B gaze
history <spell>
.PP
.B gaze
checkmd5s [spell | section | ... ]
.PP
.B gaze
depends|dependencies <spell> <level>
.SH "DESCRIPTION"
.I gaze
is part of the sorcery source-based package management suite. It is a
general purpose command-line tool for displaying package logs, version 
information, checking for installed packages, checksums, message digests,
maintainer information, package URL information, removing obsolete packages,
displaying new packages, untracked files, sections, searching for files that
are installed, finding when spells were created and packages in the
software catalogue. It can even take and retrieve snap shots of currently
installed packages for easy duplication.
.SH "OPTIONS"
.PP
.B -q
.IP
disable human style output.
.PP
.B alien
.IP
find and display all files which are not currently tracked by the
sorcery package management system
.PP
.B prune
.IP
removes all old source code and old backups. otherwise the source code from
previous versions is kept so that the packages can be rolled back to older
versions. This does not delete sources that are up to date, but not installed.

NOTE: This is deprecated. Use 
.I cleanse --sweep
.PP
.B pam
.IP
display spells installed that are pam aware
.PP
.B orphans
.IP
display installed spells that have no explicit dependencies on them
.PP
.B activity
.IP
show the activity log.
(note: this is actually a log of all that happened involving sorcery,
such as casts, summons etc.)
.PP
.B install-queue
.IP
shows the queue of spells waiting to be installed
.PP
.B remove-queue
.IP
shows the queue of spells waiting to be removed
.PP
.B show\-held
.IP
shows all spells currently held
(which means they are not to be updated)
.PP
.B show\-exiled
.IP
shows all spells currently exiled
(which means they are not to be cast in any way)
.PP
.B service
port|acronym
.IP
displays spells that provide that service
.PP
.B provides
feature
.IP
displays spells that provide the feature
.PP
.B what
spell
.IP
view the long package description
.PP
.B short
spell
.IP
view the short package description
.PP
.B where
spell
.IP
display the section a spell belongs to
.PP
.B website|url
spell
.IP
display the URL for the specified spell
.PP
.B sources
spell
.IP
list all source files contained in a spell
.PP
.B source_urls
spell
.IP
lists the urls to all files contained in a spell
.PP
.B maintainer
section
.IP
display the email address of the person currently responsible for
maintaining a specified section
.PP
.B compile
spell
.IP
show the compiler output generated when the spell was built
.PP
.B install
spell
.IP
Used to determine what files were installed by a spell and where
those files are located, excludes sorcery state files.
.PP
.B install-full
spell
.IP
Like gaze install spell, but shows sorcery state files.
.PP
.B install-spell
spell
.IP
Like gaze install spell, but excludes sorcery log files.
.PP
.B version
spell
.IP
shows the installed version of the spell and the main grimoires version.
.PP
.B versions
spell
.IP
shows the installed version of the spell and lists all available versions 
in all grimoires. If used without a spell name, then lists order of available
grimoires.
.PP
.B license
spell|section|license
.IP
view the license(s) of the given spell(s), or spells in given section(s),
or view the information about given license(s)
.PP
.B sum
<spell>
.IP
print CRC checksums for spells(s). If no spell is given it default to all.
.PP
.B md5sum
<spell>
.IP
print spell MD5 message digests (fingerprints). If no spell is given it default 
to all
.PP
.B size 
<spell>
.IP
print the size of the installed spell(s).
.PP
.B export
.IP
take a snapshot of all spells currently installed
.PP
.B import
snapshot 
.IP
restore the snapshot from a previous
.I gaze export
command (see the export option)
.PP
.B grimoire
grimoire-name
.IP
prints specified grimoire's spells or all grimoires if grimoire-name is omitted
.PP
.B grimoires
.IP
displays installed grimoires by name only
.PP
.B html
[-s] grimoire-name
.IP
prints the specified grimoire or all grimoires if grimoire-name is omitted 
in a nice html format. Additionally displays links to the source files when -s is given. 
.PP
.B search
[-name|-short] "phrase"
.IP
When omitting -name and -short searches spells name, short description and long description for
.I phrase
.IP
With -name searches spells name and with -short searches spells short description for
.I phrase
.PP
.B newer
date
.IP
print packages that are newer than a specified date. the date must be 
specified in the 'yyyymmdd' format, where y=year, m=month, and d=day
.PP
.B older
date
.IP
print packages that were first submitted before a specified date.
the date must be specified like for
.I gaze newer
.PP
.B from
<path/>file
.IP
find out what spell has installed
.I <path>/file
.PP
.B installed
[spell]
.IP
view all installed packages and corresponding version numbers or check
to see whether a particular package is installed and if it is
installed display its version number
.PP
.B section
<spell>
.IP
view a list of all sections in the software catalogue or display a list
of packages from a specific section
.PP
.B voyeur
[spell | delay]
.IP
start looking at what cast is compiling at the moment and outputs its
compiler messages. A spell can be optionally specified, or a delay
after which to abort when no casts could be found.
.PP
.B SCRIPT NAME
<spell>
.IP
replace SCRIPT NAME with any of the following 
BUILD | CONFIGURE | CONFLICTS | DETAILS | DEPENDS | FINAL | HISTORY | INSTALL | PATCH | POST_BUILD | POST_INSTALL | POST_REMOVE | PRE_BUILD | PRE_INSTALL | PRE_REMOVE | PREPARE | PROVIDES | TRIGGERS 
to show that spell script for the spell
.PP
.B history
<spell>
.IP
show history for a spell (alias for
.I gaze HISTORY <spell>
)
.PP
.B checkmd5s
[spell | section | ... ]
.IP
computes the md5sum on spell sources based on passed spell(s), section(s) or entire grimoire(s) if left blank.
.PP
.B depends
<spell> <level>
.IP
shows the spells that explicitly or recursively depend on this spell.
Up to level $level if specified.
.PP
.B dependencies
<spell> <level>
.IP
shows the spells that spell explicitly or recursively depends on.
Up to level $level if specified.
.SH "AUTHOR"
Original version written by Brian Peterson, modified by Kyle Sallee and updated 
by Thomas Stewart and Karsten Behrmann
.PP
Maintained by the Source Mage GNU Linux Team (http://www.sourcemage.org)
.SH "REPORTING BUGS"
Report bugs to bugzilla <http://bugs.sourcemage.org>
.SH "SEE ALSO"
cast(8), cleanse(8), dispel(8), grimoire(5), scribbler(8),
scribe(8), sorcery(8), sorcery_config(5), summon(8)
.SH "WARRANTY"
This is free software with ABSOLUTELY NO WARRANTY


